#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SALLab10.Resource.String.ApplicationName = global::AndroidApp.Resource.String.ApplicationName;
			global::SALLab10.Resource.String.Hello = global::AndroidApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int XamarinDiplomado = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int ClickCounter = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int ClickMe = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int ContentHeader = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int EmailText = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int EmailTextView = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int PasswordText = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int PasswordTextView = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int ValidateButton = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int ValidationText = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int imageView1 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Validate = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f060000
			public const int numberOfClicks = 2131099648;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int sound = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ButtonText = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ContentHeader = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Email = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int Password = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ValidateActivity = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
